const SUPABASE_URL="https://hxkhhnrorjxrrqxevvcr.supabase.co",SUPABASE_KEY="sb_publishable_V6MAGNlvc-PxgVMQUqnDKg_jJppxBa8",db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let profile=null,settings=null,currentView="orders";const $=s=>document.querySelector(s);const money=n=>Number(n||0).toFixed(2)+" EGP";
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2300)}
function label(s){return({new:"جديد 🔔",confirmed:"تم التأكيد",preparing:"قيد التحضير",ready:"جاهز",served:"تم التقديم",completed:"مكتمل",cancelled:"ملغي"})[s]||s}
async function boot(){const r=await db.auth.getSession();if(r.data.session)enter();else showLogin();db.auth.onAuthStateChange(function(_e,s){if(s)enter();else showLogin()})}
function showLogin(){$("#loginView").classList.remove("hidden");$("#appView").classList.add("hidden")}
async function enter(){const r=await db.from("staff_profiles").select("*").eq("user_id",(await db.auth.getUser()).data.user.id).eq("active",true).maybeSingle();if(r.error||!r.data){await db.auth.signOut();toast("هذا الحساب ليس له صلاحية إدارة.");return}profile=r.data;const s=await db.from("cafe_settings").select("*").limit(1).maybeSingle();settings=s.data;$("#staffName").textContent=profile.full_name||"Staff";$("#roleName").textContent=String(profile.role).toUpperCase();$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");renderView()}
async function renderView(){const t={orders:"الطلبات",products:"المنتجات",categories:"الأقسام",settings:"الإعدادات"};$("#viewTitle").textContent=t[currentView];document.querySelectorAll("[data-view]").forEach(function(b){b.classList.toggle("active",b.dataset.view===currentView)});if(currentView==="orders")return orders();if(currentView==="products")return products();if(currentView==="categories")return categories();return settingsView()}
async function orders(){
 const r=await db.from("orders").select("*,cafe_tables(table_number),order_items(product_name,quantity,line_total)").order("created_at",{ascending:false}).limit(100);if(r.error)return $("#view").innerHTML='<div class="notice">تعذر تحميل الطلبات.</div>';
 const rows=r.data||[],open=rows.filter(function(x){return x.status!=="completed"&&x.status!=="cancelled"}),rev=rows.filter(function(x){return x.status!=="cancelled"}).reduce(function(s,x){return s+Number(x.total)},0);
 let html='<div class="stats"><div class="stat"><small>إجمالي الطلبات</small><b>'+rows.length+'</b></div><div class="stat"><small>طلبات مفتوحة</small><b>'+open.length+'</b></div><div class="stat"><small>جاهزة</small><b>'+rows.filter(function(x){return x.status==="ready"}).length+'</b></div><div class="stat"><small>الإجمالي</small><b>'+money(rev)+'</b></div></div><div class="orders">';
 html+=rows.length?rows.map(function(o){let items=(o.order_items||[]).map(function(i){return '<div class="item-row"><span>'+i.quantity+" × "+i.product_name+"</span><b>"+money(i.line_total)+"</b></div>"}).join("");let opts=["new","confirmed","preparing","ready","served","completed","cancelled"].map(function(s){return '<option value="'+s+'" '+(s===o.status?"selected":"")+'>'+label(s)+"</option>"}).join("");return '<article class="order-card"><div class="order-top"><div><div class="order-no">#'+o.order_number+'</div><span class="table-tag">طاولة '+(o.cafe_tables?o.cafe_tables.table_number:"—")+"</span></div><span class=\"price\">"+money(o.total)+'</span></div><div class="items">'+items+'</div><div class="status-row"><select class="status-select" data-status="'+o.id+'">'+opts+"</select><small>"+new Date(o.created_at).toLocaleString("ar-EG")+"</small></div></article>"}).join(""):'<div class="notice">لا توجد طلبات حتى الآن.</div>';
 $("#view").innerHTML=html+"</div>";document.querySelectorAll("[data-status]").forEach(function(s){s.onchange=async function(){const r=await db.from("orders").update({status:s.value,updated_at:new Date().toISOString()}).eq("id",s.dataset.status);if(r.error)toast("تعذر تحديث الحالة");else orders()}})
}
async function products(){
 const r=await Promise.all([db.from("products").select("*,categories(name)").order("sort_order"),db.from("categories").select("id,name").eq("active",true).order("sort_order")]),rows=r[0].data||[],cats=r[1].data||[];
 let html='<div class="toolbar"><button class="primary-btn" id="newProduct">+ إضافة منتج</button><input id="productSearch" placeholder="بحث…"></div><div class="table-wrap"><table class="data-table"><thead><tr><th>المنتج</th><th>القسم</th><th>السعر</th><th>الحالة</th><th></th></tr></thead><tbody>';
 html+=rows.map(function(x){return '<tr><td>'+x.name+"</td><td>"+(x.categories?x.categories.name:"—")+"</td><td class=\"price\">"+money(x.price)+"</td><td>"+(x.active?"نشط":"مخفي")+'</td><td><button class="btn-small" data-toggle="'+x.id+'" data-active="'+x.active+'">'+(x.active?"إخفاء":"تفعيل")+"</button></td></tr>"}).join("")+"</tbody></table></div>";$("#view").innerHTML=html;
 $("#newProduct").onclick=function(){productForm(cats)};$("#productSearch").oninput=function(e){document.querySelectorAll("tbody tr").forEach(function(r){r.style.display=r.textContent.includes(e.target.value)?"":"none"})};document.querySelectorAll("[data-toggle]").forEach(function(b){b.onclick=async function(){await db.from("products").update({active:b.dataset.active!=="true",updated_at:new Date().toISOString()}).eq("id",b.dataset.toggle);products()}})
}
function productForm(cats){let opts=cats.map(function(c){return '<option value="'+c.id+'">'+c.name+"</option>"}).join("");$("#view").innerHTML='<div class="form-card"><div class="notice">إضافة منتج جديد للمنيو.</div><form id="pf" class="form-grid"><label>اسم المنتج<input name="name" required></label><label>السعر<input name="price" type="number" step=".01" required></label><label>القسم<select name="category_id">'+opts+'</select></label><label>رابط الصورة<input name="image_url"></label><label>الوصف<input name="description"></label><div><button class="primary-btn">حفظ المنتج</button></div></form></div>';$("#pf").onsubmit=async function(e){e.preventDefault();const f=new FormData(e.target),r=await db.from("products").insert({name:f.get("name"),price:Number(f.get("price")),category_id:f.get("category_id"),image_url:f.get("image_url")||null,description:f.get("description")||null,active:true});if(r.error)return toast("تعذر إضافة المنتج");toast("تمت إضافة المنتج");products()}}
async function categories(){const r=await db.from("categories").select("*").order("sort_order");let rows=r.data||[];$("#view").innerHTML='<div class="toolbar"><button class="primary-btn" id="newCat">+ إضافة قسم</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>القسم</th><th>الاسم الإنجليزي</th><th>الحالة</th></tr></thead><tbody>'+rows.map(function(x){return "<tr><td>"+(x.icon||"•")+" "+x.name+"</td><td>"+(x.name_en||"—")+"</td><td>"+(x.active?"نشط":"مخفي")+"</td></tr>"}).join("")+"</tbody></table></div>";$("#newCat").onclick=async function(){const name=prompt("اسم القسم:");if(name){await db.from("categories").insert({name,active:true});categories()}}}
async function settingsView(){if(!settings){const r=await db.from("cafe_settings").select("*").limit(1).maybeSingle();settings=r.data}$("#view").innerHTML='<div class="form-card"><h3>إعدادات الفاتورة</h3><form id="sf" class="form-grid"><label>اسم الكافيه<input name="cafe_name" value="'+(settings.cafe_name||"A&S Café")+'"></label><label>العملة<input name="currency" value="'+(settings.currency||"EGP")+'"></label><label>الضريبة %<input name="tax_percent" type="number" step=".01" value="'+settings.tax_percent+'"></label><label>الخدمة %<input name="service_percent" type="number" step=".01" value="'+settings.service_percent+'"></label><div><button class="primary-btn">حفظ</button></div></form></div>';$("#sf").onsubmit=async function(e){e.preventDefault();const f=new FormData(e.target),r=await db.from("cafe_settings").update({cafe_name:f.get("cafe_name"),currency:f.get("currency"),tax_percent:Number(f.get("tax_percent")),service_percent:Number(f.get("service_percent")),updated_at:new Date().toISOString()}).eq("id",settings.id);if(r.error)toast("تعذر الحفظ");else{toast("تم حفظ الإعدادات");settings.cafe_name=f.get("cafe_name");settings.currency=f.get("currency");settings.tax_percent=Number(f.get("tax_percent"));settings.service_percent=Number(f.get("service_percent"))}}}
document.querySelectorAll("[data-view]").forEach(function(b){b.onclick=function(){currentView=b.dataset.view;renderView()}});$("#loginForm").onsubmit=async function(e){e.preventDefault();const r=await db.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(r.error)toast("البريد أو كلمة المرور غير صحيحة")};$("#logout").onclick=function(){db.auth.signOut()};boot();